import type { Metadata } from "next";
import posthog from "posthog-js";

import "../styles/globals.css";
import { ThemeProvider } from "@/components/theme-provider";
import { josefin } from "../styles/fonts";

export const metadata: Metadata = {
  title: "Pivot Link",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="dark" suppressHydrationWarning>
      <body className={`${josefin.variable} ${josefin.variable} antialiased`}>
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}

const POSTHOG_API_KEY = process.env.NEXT_PUBLIC_POSTHOG_KEY || "";

if (
  typeof window !== "undefined" &&
  POSTHOG_API_KEY &&
  process.env.NODE_ENV === "production"
) {
  posthog.init(POSTHOG_API_KEY, {
    api_host: "https://app.posthog.com",
  });
} else {
  if (typeof window !== "undefined") {
    console.warn(
      "[PostHog] Skipped initialization: Missing API key or not production."
    );
  }
}
